# Generated by Django 5.2.1 on 2025-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_cc_1_alter_cliente_cc_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailenviado',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos/'),
        ),
    ]
