# Generated by Django 5.2.1 on 2025-06-01 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_credencialessmtp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credencialessmtp',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='credencialessmtp',
            name='smtp_usuario',
        ),
        migrations.AddField(
            model_name='credencialessmtp',
            name='smtp_puerto',
            field=models.IntegerField(default=465),
        ),
        migrations.AddField(
            model_name='credencialessmtp',
            name='smtp_user',
            field=models.EmailField(default=465, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credencialessmtp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
