# Generated by Django 5.2.1 on 2025-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_credencialessmtp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialessmtp',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
